---
- name: enable packet forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: setup iptables directory
  file: path="/etc/iptables/" state=directory mode=0700

- name: setup iptables NAT rules
  copy: src=rules.v4 dest=/etc/iptables/rules.v4

- name: Install iptables oneshot service
  copy: src=iptables.service dest=/etc/systemd/system/iptables.service mode=0644
  register: iptables_service
  notify:
    - reload systemd
    - restart iptables

