---
- include: packages_yum.yml
  when: ansible_os_family == 'RedHat'

- include: packages_apt.yml
  when: ansible_os_family == 'Debian'

- include: configure-server.yml

- include: forward-traffic.yml
  when: legos_openvpn_forward_traffic
