---
- name: apt-get update if the last one is more than 3600 seconds ago
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages
  apt: pkg="{{ item }}" state=latest force=yes
  with_items:
    - openvpn
    - udev
    - iptables

- name: Install awscli via pip
  pip: name=awscli
  become: True

- name: Install LDAP dependencies
  apt: pkg="openvpn-auth-ldap" state=latest force=yes
  when: legos_openvpn_use_ldap
